import { describe, expect, test, vi } from 'vitest'
import { BookmarkOrchestrator } from '../../src/domain/orchestrator/bookmark'
import { createMockCtx } from '../helpers/mockFactory'
import { resolveBookmarkReadAccess } from '@/utils/bookmarkAccess'

function createWriter() {
  const chunks: string[] = []
  const writer = new WritableStream<Uint8Array>({
    write(chunk) {
      chunks.push(new TextDecoder().decode(chunk))
    }
  }).getWriter()

  return {
    writer,
    output: () => chunks.flatMap(chunk => chunk.trim().split('\n')).filter(Boolean).map(line => JSON.parse(line))
  }
}

function wire() {
  const repo = {
    getUserBookmarkByUuidWithDetail: vi.fn().mockResolvedValue({
      user_id: 10,
      bookmark_id: 42,
      deleted_at: null,
      bookmark: { moderation_result: 0 }
    }),
    getBookmarkShareByBookmarkId: vi.fn().mockResolvedValue(null)
  }
  const userRepo = { getInfoByUserId: vi.fn().mockResolvedValue({ snapshot_sharing: true }) }
  const bookmarkService = {
    getBookmarkReadAccess: (ctx: any, uuid: string) => resolveBookmarkReadAccess(repo as any, userRepo as any, ctx.getUserId(), uuid),
    getBookmarkId: vi.fn().mockResolvedValue(0),
    getUserBookmarkOverview: vi.fn(),
    getBookmarkOutline: vi.fn(),
    getUserBookmarkSummary: vi.fn(),
    getBookmarkTitleContent: vi.fn()
  }
  const tagService = { getBookmarkTags: vi.fn() }
  const aigcService = {
    generateOverviewTag: vi.fn(),
    generateSummary: vi.fn()
  }
  const orchestrator = new BookmarkOrchestrator(
    bookmarkService as any,
    tagService as any,
    {} as any,
    {} as any,
    {} as any,
    aigcService as any,
    {} as any,
    (() => ({})) as any
  )

  return { orchestrator, bookmarkService, tagService, aigcService, repo, userRepo }
}

describe('Collection bookmark AI data', () => {
  test('returns the overview generated by the owner', async () => {
    const { orchestrator, bookmarkService, tagService } = wire()
    bookmarkService.getUserBookmarkOverview.mockResolvedValue({
      content: JSON.stringify({ overview: 'owner overview', key_takeaways: ['owner takeaway'] })
    })
    const stream = createWriter()

    await orchestrator.generateBookmarkOverviewStream(createMockCtx({ userId: 20 }), {
      bmUId: 'owner-bookmark-uuid',
      writer: stream.writer,
      encoder: new TextEncoder(),
      isForce: false
    })

    expect(bookmarkService.getUserBookmarkOverview).toHaveBeenCalledWith(10, 42)
    expect(tagService.getBookmarkTags).not.toHaveBeenCalled()
    expect(stream.output()).toEqual([
      { type: 'progress', data: { overview: 'owner overview' } },
      { type: 'progress', data: { key_takeaways: ['owner takeaway'] } },
      { type: 'progress', data: { done: true } }
    ])
  })

  test('returns the outline generated by the owner', async () => {
    const { orchestrator, bookmarkService } = wire()
    bookmarkService.getBookmarkOutline.mockResolvedValue('owner outline')
    const stream = createWriter()

    await orchestrator.generateBookmarkOutlineStream(createMockCtx({ userId: 20 }), {
      bmUId: 'owner-bookmark-uuid',
      writer: stream.writer,
      encoder: new TextEncoder(),
      isForce: false
    })

    expect(bookmarkService.getBookmarkOutline).toHaveBeenCalledWith(42, 10)
    expect(bookmarkService.getUserBookmarkSummary).not.toHaveBeenCalled()
    expect(stream.output()).toEqual([
      { type: 'progress', data: { outline: 'owner outline' } },
      { type: 'progress', data: { done: true } }
    ])
  })

  test('does not generate missing owner overview or outline', async () => {
    const { orchestrator, bookmarkService, aigcService } = wire()
    bookmarkService.getUserBookmarkOverview.mockResolvedValue(null)
    bookmarkService.getBookmarkOutline.mockResolvedValue(null)
    const overviewStream = createWriter()
    const outlineStream = createWriter()
    const ctx = createMockCtx({ userId: 20 })

    await orchestrator.generateBookmarkOverviewStream(ctx, {
      bmUId: 'owner-bookmark-uuid',
      writer: overviewStream.writer,
      encoder: new TextEncoder(),
      isForce: false
    })
    await orchestrator.generateBookmarkOutlineStream(ctx, {
      bmUId: 'owner-bookmark-uuid',
      writer: outlineStream.writer,
      encoder: new TextEncoder(),
      isForce: false
    })

    expect(overviewStream.output()).toEqual([{ type: 'progress', data: { done: true } }])
    expect(outlineStream.output()).toEqual([{ type: 'progress', data: { done: true } }])
    expect(bookmarkService.getBookmarkTitleContent).not.toHaveBeenCalled()
    expect(aigcService.generateOverviewTag).not.toHaveBeenCalled()
    expect(aigcService.generateSummary).not.toHaveBeenCalled()
  })

  test.each(['disabled', 'global-off', 'deleted', 'moderated', 'missing'])('denies %s before reading any AI cache', async reason => {
    const { orchestrator, bookmarkService, repo, userRepo } = wire()
    if (reason === 'disabled') repo.getBookmarkShareByBookmarkId.mockResolvedValue({ is_enable: false } as never)
    if (reason === 'global-off') userRepo.getInfoByUserId.mockResolvedValue({ snapshot_sharing: false })
    if (reason === 'deleted') repo.getUserBookmarkByUuidWithDetail.mockResolvedValue({ user_id: 10, bookmark_id: 42, deleted_at: new Date(), bookmark: { moderation_result: 0 } } as never)
    if (reason === 'moderated') repo.getUserBookmarkByUuidWithDetail.mockResolvedValue({ user_id: 10, bookmark_id: 42, deleted_at: null, bookmark: { moderation_result: 1 } })
    if (reason === 'missing') repo.getUserBookmarkByUuidWithDetail.mockResolvedValue(null as never)
    bookmarkService.getUserBookmarkOverview.mockResolvedValue({ overview: 'secret' })
    bookmarkService.getBookmarkOutline.mockResolvedValue('secret')

    for (const method of ['generateBookmarkOverviewStream', 'generateBookmarkOutlineStream'] as const) {
      const stream = createWriter()
      await orchestrator[method](createMockCtx({ userId: 20 }), {
        bmUId: 'owner-bookmark-uuid', writer: stream.writer, encoder: new TextEncoder(), isForce: false
      })
      expect(stream.output()).toEqual([{ type: 'progress', data: { done: true } }])
    }
    expect(bookmarkService.getUserBookmarkOverview).not.toHaveBeenCalled()
    expect(bookmarkService.getBookmarkOutline).not.toHaveBeenCalled()
  })
})
